version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  build:
    commands:
      - pwd
      - aws cloudformation package --template-file template.yaml --output-template-file finalpackage.yaml --s3-bucket <bucket_name>

artifacts:
  type: zip
  files:
    - finalpackage.yaml
